version: '3.8'

services:
  pa11y:
    build: ./

    ports:
      - "80:3333"
      - "4000:4000"
    depends_on:
      - mongo
    links:
      - mongo
    tty: true
    env_file: .env

  mongo:
    image: mongo:latest
